# Generated by Django 4.0.3 on 2022-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FilePathField(default='', path='/home/edno/Desktop/portfolio/Portfolio-website-using-django/myportfolio/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='/home/edno/Desktop/portfolio/Portfolio-website-using-django/myportfolio/static/img'),
        ),
    ]
