# Generated by Django 4.0.3 on 2022-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_rename_fb_link_profile_medium_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag1',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tag2',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tag3',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
