# Generated by Django 4.0.3 on 2022-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_alter_project_tag1_alter_project_tag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
