# Generated by Django 4.0.3 on 2022-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_alter_project_tag1_alter_project_tag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medium_link',
            field=models.URLField(blank=True, default=None),
        ),
    ]
